const data = {
    products:[
        {
            _id:'1',
            name:'Anthurium Clarinervium',
            category: 'house plants',
            image: '/assets/anthurium-1.jpg',
            price: 20,
            rating: 4.7,
            numReviews: 12,
            description: 'very nice plant',
            countInStock: 12,
        },
        {
            _id:'2',
            name:'Strelitzia nicolai',
            category: 'house plants',
            image: '/assets/banana-1.jpg',
            price: 60,
            rating: 4.2,
            numReviews: 32,
            description: 'very nice plant',
            countInStock: 1432,
        },
        {
            _id:'3',
            name:'Arcea palm',
            category: 'house plants',
            image: '/assets/fern-1.jpg',
            price: 30,
            rating: 4.5,
            numReviews: 10,
            description: 'very nice plant',
            countInStock: 1,
        },
        {
            _id:'4',
            name:'String of hearts plant',
            category: 'house plants',
            image: '/assets/hearts-1.jpg',
            price: 15,
            rating: 5,
            numReviews: 2,
            description: 'very nice plant',
            countInStock: 343,
        },
        {
            _id:'5',
            name:'Jewel orchid',
            category: 'house plants',
            image: '/assets/jewel-1.jpg',
            price: 15,
            rating: 4.1,
            numReviews: 38,
            description: 'very nice plant',
            countInStock: 0,
        },
        {
            _id:'6',
            name:'Maranta leuconeura',
            category: 'house plants',
            image: '/assets/maranta-1.jpg',
            price: 25,
            rating: 3.9,
            numReviews: 74,
            description: 'very nice plant',
            countInStock: 3432,
        },
        {
            _id:'7',
            name:'Monstera plant',
            category: 'house plants',
            image: '/assets/monstera-1.jpg',
            price: 70,
            rating: 2.2,
            numReviews: 1,
            description: 'very nice plant',
            countInStock: 34,
        },
        {
            _id:'8',
            name:'Peacock plant',
            category: 'house plants',
            image: '/assets/peacock-1.jpg',
            price: 20,
            rating: 1,
            numReviews: 1,
            description: 'very nice plant',
            countInStock: 12,
        },
        {
            _id:'9',
            name:'Pilea plant',
            category: 'house plants',
            image: '/assets/pilea-1.jpg',
            price: 10,
            rating: 4.5,
            numReviews: 134,
            description: 'very nice plant',
            countInStock: 0,
        },
        {
            _id:'10',
            name:'Robusta plant',
            category: 'house plants',
            image: '/assets/robusta-1.jpg',
            price: 25,
            rating: 5,
            numReviews: 23,
            description: 'very nice plant',
            countInStock: 2,
        },
        {
            _id:'11',
            name:'Scindapsus picuts',
            category: 'house plants',
            image: '/assets/silver-1.jpg',
            price: 15,
            rating: 4.5,
            numReviews: 17,
            description: 'very nice plant',
            countInStock: 754,
        },
        {
            _id:'12',
            name:'Sansevieria trifasciata zeylanica',
            category: 'house plants',
            image: '/assets/zebra-1.jpg',
            price: 20,
            rating: 3.3,
            numReviews: 7,
            description: 'very nice plant',
            countInStock: 234,
        },
        {
            _id:'13',
            name:'ZZ plant',
            category: 'house plants',
            image: '/assets/zz-1.jpg',
            price: 35,
            rating: 4.9,
            numReviews: 120,
            description: 'very nice plant',
            countInStock: 0,
        },
    ]
}

export default data